### ISSUE TITLE
Bug: Bass D- and E-string tuning does not work properly

### ISSUE THREAD

**Issue by retki** [brianhorn/Tunerly#18]
Tunerly does not recognize the sound properly.

**Comment by brianhorn** [comment]
This is a bit of a difficult subject as it's not something I have a lot of control over - some reasons behind this were also discussed in #5.

One value I can change is in which range a note is recognized. Changing this value is most noticeable in lower ranges, as when I set it to be too narrow lower strings are recognized less reliably. 

I tried to find a range (which currently is 10 cents) that offers reliable tuning, but also works well enough with lower strings. As a testing point for "almost worst case low range instrument" I took a 5 string electric bass unamplified. In my case this works great actually, so I'm a bit surprised it doesn't seem to work for you. I also included 6 string bass, but honestly I'm not sure that's generally something that can be accurately built into a smartphone tuner and I don't have one to try out. 

But as I said, there are external factors to this. Specific smartphone (different microphones), smartphone position, ambient volume, specific instrument, amplified/unamplified, strings, how the instrument is picked...

The only place apart from changing the tuning range where one could change something that could effect how well one could tune a bass would be the pitch detection algorithm - there are a few standard, widely used algorithms out there, which of course I just use instead of implementing my own one (that would be nuts, way too much work for something that would not work well in the end), so I don't have a lot of hope that I could improve this - but still I'm interested, what is your setup when tuning bass with Tunerly?
