### ISSUE TITLE
Make "tuned" range narrower

### ISSUE THREAD

**Issue by Porrumentzio** [brianhorn/Tunerly#5]
Currently that range in which both arrows get green is some cents wide. I would like to make that range narrower, because it seems more accurate.
I would change this by design, not as an option (or both).

**Comment by brianhorn** [comment]
The range in which it shows to be in tune is currently set to 10 cents. Since there are 100 cents in a semitone that is 1/10th of a semitone. The JND (just noticable difference) for humans is of course heavily dependent on a lot of factors and there are different studies with different results on this, however it seems to be somewhere between 5 to 12 cents from what I read. Also when playing scales on a piano that are farther away from C Major there are differences of up to 14 cents which the human ear adjusts automatically.

I work in a music school and talked about what range some colleagues would find acceptable and so far I haven't heard complaints about 10 cents. 

When setting this value it is important to find a good compromise between accuracy and stability. If I would change the range to 1 cent you would barely see both arrows green, it would just flash quickly. I started with 5 cents which was not stable at all, and I found 10 cents to both be accurate and still stable. 

I'm curious, how did you find the tuner to be a bit inaccurate? I have tried it alongside my trusty old korg ca-50 and I could tune my instruments equally well with both (I used the microphone and not input jack with the Korg).

**Comment by Porrumentzio** [comment]
Hi! Thanks for the answer!

I'm musician too and I have the sense that tuning with Tunerly does not create a tuned harmony on the guitar, while tuning with the incorporated tuner on the guitar yes (this is a contact microphone tuner, so maybe there's the difference)
Tuning with Korg CA-30 was also a bit more accurate as it indicates a bar moving through the cents.

This issue is not a common one because many people will find Tunerly perfect, while other ones, mainly those that have been playing music for years, will have a non-harmonic sense.

What about trying with 8 cents?

**Comment by brianhorn** [comment]
Well hardware tuners are (...or at least should) always be more accurate than a smartphone tuner, even if it might be unnoticeable to some people.

It would be interesting to know what difference the smartphone microphone has on the accuracy - I'm sure it does have a non-negligible impact on tuning accuracy, but I'm not sure how to gather reliable and meaningful data about this. 

The problem when making the tuning range more narrow is most noticeable in the lower frequency response. Setting it to 8 Hz makes the low E string on the Guitar quite unstable to show as tuned, I didn't try a Bass Guitar now but it would be even more noticeable there (on Guitar I always test with an acoustic Guitar and an unplugged electric Guitar - response is generally worse on unplugged electric Guitar of course, but setting the range to 8 Hz is even problematic on acoustic Guitar). 

For this reason I think "sacrificing" those two cents in favor of stability makes more sense. And sure, in general this is heavily dependent on the person using the app, someone with perfect pitch will obviously immediately hear that the string is not 100% in tune as soon as both arrows show green - but a 10th of a semitone (remember, this is the "worst case" so to speak as you often easily tune just a bit more when the arrows hit green)  is a range that features some practical accuracy while not making the tuner a pain to use because it never shows in tune for more than a millisecond on lower strings.

**Comment by Porrumentzio** [comment]
It's a pleasure to speak with you! Thanks for the explanations, I didn't think about range on low sound frequency!

I understand you. Another option I thought is to change the color gradually while approximating to exact pitch:

10 cents > dark green
8 cents > no so dark green
5 cents > actual green

Maybe this is a feature that requires many work and does not deserve it, as for many people this is not noticeable. I'll close this issue for not bothering, but we could speak further
